### ISSUE TITLE
Unable to Read EventMarkers from the path file

### ISSUE THREAD

**Issue by WinstonHChou** [jsimpso81/PathPlannerLabVIEW#5]
just want to make sure if the library is able to read EventMarkers now?

**Comment by jsimpso81** [comment]
Yes it can read them.  I dont have code to execute them but the array of clusters is created.  On Dec 22, 2023, at 9:38 PM, Winston ***@***.***> wrote:﻿
just want to make sure if the library is able to read EventMarkers now?

**Comment by WinstonHChou** [comment]
![image](https://github.com/jsimpso81/PathPlannerLabVIEW/assets/68310078/71e4f134-7cc7-4719-ad1d-6e395713fdf8)
![image](https://github.com/jsimpso81/PathPlannerLabVIEW/assets/68310078/97bd98d0-41bc-4d3e-b235-e94a55532509)
![image](https://github.com/jsimpso81/PathPlannerLabVIEW/assets/68310078/e5839754-04f0-46a1-b5fe-b2f37d9d950f)

I established some eventmarkers on the path, and use EventMarker_FromJSON.vi to read them, but it didn't work

**Comment by WinstonHChou** [comment]
![image](https://github.com/jsimpso81/PathPlannerLabVIEW/assets/68310078/a87def17-bdce-4e7c-8e56-dbaf2deeebb3)
![image](https://github.com/jsimpso81/PathPlannerLabVIEW/assets/68310078/7c30cc71-04da-4c09-9031-29e7196a8581)
![image](https://github.com/jsimpso81/PathPlannerLabVIEW/assets/68310078/718f5f08-e2a1-44c4-a2b4-def781e153c3)
I established some eventmarkers on the path, and it did read and generate a trajectory. But it did not read the eventmarkers.

**Comment by jsimpso81** [comment]
Can you attach the path file to help me diagnose

**Comment by WinstonHChou** [comment]
________________________________
寄件者: Jim S. ***@***.***>
寄件日期: 2023年12月25日 上午 02:21
收件者: jsimpso81/PathPlannerLabVIEW ***@***.***>
副本: Winston ***@***.***>; Author ***@***.***>
主旨: Re: [jsimpso81/PathPlannerLabVIEW] Unable to Read EventMarkers from the path file (Issue #5)


Can you attach the path file to help me diannise

**Comment by jsimpso81** [comment]
The event marker parsing was re-written.  The changes are contained in the Beta-2 release.  Let me know if this fixes the issue.

The current event marker parsing only supports 2 levels of commands.  The first level can be "sequential", "parallel", "deadline", or "race".  The second level can contain an array of commands that can be "named", "wait", or "path"  The second level will parse "sequential", "parallel", "deadline", or "race", but it will not parse the 3rd level commands below that.   I think that this matches the intent of the java/c implementation.   

If this fixes your issue, go ahead and close it as fixed.

**Comment by jsimpso81** [comment]
Just wondered if you were able to try the fix yet?

**Comment by WinstonHChou** [comment]
![image](https://github.com/jsimpso81/PathPlannerLabVIEW/assets/68310078/2fee077c-9808-4fb9-bcd9-747ced0f489a)
Yeah, it works!

sry for late reply, just got back to college after my winter break
